version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports: ["80:80"]
    volumes: ["./:/usr/share/nginx/html"]

  backend-java:
    build: ./backend-java
    ports: ["8080:8080"]

  ai-python:
    build: ./ai-python
    ports: ["5000:5000"]

  service-native:
    build: ./service-native

  service-csharp:
    build: ./service-csharp
    
